// =============================================================================
// display.sv — Top-Level Game Module
// =============================================================================
// This is the top-level module for the Pac-Man FPGA implementation.
// It instantiates and connects all subsystems: VGA output, ADC joystick input,
// Pac-Man and ghost controllers, dot tracking, score, audio, and screen ROMs.
// The game state machine lives here and manages transitions between the title,
// gameplay, win, and lose screens.
// =============================================================================

module display(
    // -------------------------------------------------------------------------
    // Clock and Reset
    // -------------------------------------------------------------------------
    input  logic        clock,      // 50MHz system clock
    input  logic        reset_n,    // Active-low reset

    // -------------------------------------------------------------------------
    // ADC Interface (Joystick — SPI)
    // -------------------------------------------------------------------------
    input  logic        SDO,        // ADC serial data out (joystick)
    output logic        SDI,        // ADC serial data in
    output logic        SCLK,       // ADC serial clock
    output logic        CS_N,       // ADC chip select (active low)

    // -------------------------------------------------------------------------
    // Button Inputs
    // -------------------------------------------------------------------------
    input  logic        KEY0,       // Start game button
    input  logic        KEY2,       // Cheat mode toggle

    // -------------------------------------------------------------------------
    // VGA Output
    // -------------------------------------------------------------------------
    output logic        sync_n,     // VGA composite sync
    output logic        blank_n,    // VGA blanking signal
    output logic        hsync_n,    // VGA horizontal sync
    output logic        vsync_n,    // VGA vertical sync
    output logic [7:0]  red,        // VGA red channel
    output logic [7:0]  green,      // VGA green channel
    output logic [7:0]  blue,       // VGA blue channel
    output logic        vga_clock,  // 25MHz pixel clock for VGA

    // -------------------------------------------------------------------------
    // Audio Output
    // -------------------------------------------------------------------------
    output logic        speaker_out,// PWM audio output

    // -------------------------------------------------------------------------
    // Seven-Segment Score Display
    // -------------------------------------------------------------------------
    output logic [6:0]  HEX0,       // Score digit 0
    output logic [6:0]  HEX1,       // Score digit 1
    output logic [6:0]  HEX2,       // Score digit 2
    output logic [6:0]  HEX3,       // Score digit 3
    output logic [6:0]  HEX4,       // Score digit 4
    output logic [6:0]  HEX5        // Score digit 5
);

    // -------------------------------------------------------------------------
    // VGA Beam Position
    // -------------------------------------------------------------------------
    logic [9:0]  hcount, vcount;    // Current pixel coordinates from vga_controller
    logic        vga_clk_int;       // 25MHz pixel clock generated by PLL

    // -------------------------------------------------------------------------
    // Pac-Man Position and Direction
    // -------------------------------------------------------------------------
    logic [9:0]  pac_x, pac_y;      // Pac-Man pixel position
    logic [1:0]  direction;         // Current movement direction
    logic        moving_out;        // High when Pac-Man is actively moving
    logic [9:0]  pac_tile_x, pac_tile_y; // Tile coordinates for win condition check

    // -------------------------------------------------------------------------
    // Ghost Positions and Directions
    // ghost  = waypoint follower 1
    // rghost = replay buffer ghost (mirrors Pac-Man's path with delay)
    // ghost3 = waypoint follower 3
    // ghost4 = waypoint follower 4
    // -------------------------------------------------------------------------
    logic [9:0]  ghost_x,  ghost_y;
    logic [9:0]  rghost_x, rghost_y;
    logic [9:0]  ghost3_x, ghost3_y;
    logic [9:0]  ghost4_x, ghost4_y;
    logic [1:0]  ghost_dir;
    logic [1:0]  ghost2_dir;
    logic [1:0]  ghost3_dir;
    logic [1:0]  ghost4_dir;

    // -------------------------------------------------------------------------
    // ROM/RAM Addressing
    // -------------------------------------------------------------------------
    logic [18:0] vga_addr;   // Current pixel address into maze ROM (640x480)
    logic [18:0] col_addr;   // Lookahead address for wall collision detection
    logic [16:0] title_addr; // Address into title/win/lose screen ROMs (320x240)
    logic        pixel_data; // 1 = wall pixel at vga_addr
    logic        col_pixel;  // 1 = wall pixel at col_addr (used for movement checks)

    // -------------------------------------------------------------------------
    // Dot System
    // -------------------------------------------------------------------------
    logic        dot_alive;  // 1 = dot at current vga_addr has not been eaten
    logic        dot_eaten;  // Pulse when a dot is consumed (triggers score increment)
    logic        eat;        // Signal from pac_controller: Pac-Man is over a dot
    logic [18:0] eat_addr;   // Address of the dot being eaten

    // -------------------------------------------------------------------------
    // Score
    // -------------------------------------------------------------------------
    logic [15:0] score;      // Counts eaten dot pixels; win triggers at 14256

    // -------------------------------------------------------------------------
    // Joystick ADC Readings
    // -------------------------------------------------------------------------
    logic [11:0] joystick_lr, joystick_ud; // Raw 12-bit ADC values

    // -------------------------------------------------------------------------
    // Game State
    // 2'd0 = title screen
    // 2'd1 = gameplay
    // 2'd2 = lose screen
    // 2'd3 = win screen
    // -------------------------------------------------------------------------
    logic [1:0]  game_state;
    logic        title_active;
    logic        game_active;
    logic        game_over;
    logic        win;

    // -------------------------------------------------------------------------
    // Screen Image Pixel Outputs
    // -------------------------------------------------------------------------
    logic        title_pixel;
    logic        lose_pixel;
    logic        win_pixel;

    // -------------------------------------------------------------------------
    // Audio
    // -------------------------------------------------------------------------
    logic        music_out; // Pac-Man theme (title screen)
    logic        waka_out;  // Waka waka sound (gameplay)

    // -------------------------------------------------------------------------
    // Button Edge Detection
    // -------------------------------------------------------------------------
    logic        key0_prev; // Previous cycle value of KEY0
    logic        key2_prev; // Previous cycle value of KEY2

    // -------------------------------------------------------------------------
    // Immunity Timer and Cheat Mode
    // -------------------------------------------------------------------------
    logic [27:0] immunity_cnt; // Counts up to 250M cycles (5 seconds at 50MHz)
    logic        immune;       // High during immunity window after game start
    logic        cheat_mode;   // When active, all ghosts rendered off-screen

    // -------------------------------------------------------------------------
    // Game State Flag Assignments
    // -------------------------------------------------------------------------
    assign title_active = (game_state == 2'd0);
    assign game_active  = (game_state == 2'd1);
    assign game_over    = (game_state == 2'd2);
    assign win          = (game_state == 2'd3);

    // Route audio based on current screen state
    assign speaker_out = (game_state == 2'd0) ? music_out :
                         (game_state == 2'd1) ? waka_out  : 1'b0;

    // -------------------------------------------------------------------------
    // Game State Machine
    // Handles: screen transitions, immunity timer, button edge detection,
    // win condition (all dots eaten + return to center), lose condition
    // (ghost bounding box overlap with Pac-Man after immunity expires)
    // -------------------------------------------------------------------------
    always_ff @(posedge clock or negedge reset_n) begin
        if (!reset_n) begin
            game_state   <= 2'd0;
            key0_prev    <= 1;
            key2_prev    <= 1;
            immunity_cnt <= 0;
            immune       <= 1;
            cheat_mode   <= 0;
        end else begin
            key0_prev <= KEY0;
            key2_prev <= KEY2;

            // Toggle cheat mode on KEY2 falling edge
            if (key2_prev && !KEY2)
                cheat_mode <= ~cheat_mode;

            // Immunity timer: Pac-Man immune for 5 seconds after game starts
            if (game_active) begin
                if (immunity_cnt < 28'd250_000_000) begin
                    immunity_cnt <= immunity_cnt + 1;
                    immune       <= 1;
                end else
                    immune <= 0;
            end else begin
                immunity_cnt <= 0;
                immune       <= 1;
            end

            // KEY0 falling edge on title screen → start game
            if (key0_prev && !KEY0 && game_state == 2'd0)
                game_state <= 2'd1;

            if (game_state == 2'd1) begin
                // Win: all dots eaten and Pac-Man returned to center (300-320x, 200-220y)
                if ((score == 16'd14256) &&
                    (pac_x >= 10'd300 && pac_x <= 10'd320) &&
                    (pac_y >= 10'd200 && pac_y <= 10'd220))
                    game_state <= 2'd3;

                // Lose: any ghost AABB overlaps Pac-Man's inner 24x24 bounding box
                // Only active after immunity expires; disabled in cheat mode
                else if (!immune && !cheat_mode && (
                    (ghost_x < 10'd640 &&
                     ghost_x  + 10'd24 >= pac_x + 10'd8 && ghost_x  + 10'd8 <= pac_x + 10'd24 &&
                     ghost_y  + 10'd24 >= pac_y + 10'd8 && ghost_y  + 10'd8 <= pac_y + 10'd24) ||
                    (rghost_x < 10'd640 &&
                     rghost_x + 10'd24 >= pac_x + 10'd8 && rghost_x + 10'd8 <= pac_x + 10'd24 &&
                     rghost_y + 10'd24 >= pac_y + 10'd8 && rghost_y + 10'd8 <= pac_y + 10'd24) ||
                    (ghost3_x < 10'd640 &&
                     ghost3_x + 10'd24 >= pac_x + 10'd8 && ghost3_x + 10'd8 <= pac_x + 10'd24 &&
                     ghost3_y + 10'd24 >= pac_y + 10'd8 && ghost3_y + 10'd8 <= pac_y + 10'd24) ||
                    (ghost4_x < 10'd640 &&
                     ghost4_x + 10'd24 >= pac_x + 10'd8 && ghost4_x + 10'd8 <= pac_x + 10'd24 &&
                     ghost4_y + 10'd24 >= pac_y + 10'd8 && ghost4_y + 10'd8 <= pac_y + 10'd24)))
                    game_state <= 2'd2;
            end
        end
    end

    // -------------------------------------------------------------------------
    // Title/Win/Lose Screen ROM Address
    // Computes address into 320x240 ROM centered within the 640x480 display
    // Returns 0 if beam is outside the centered region
    // -------------------------------------------------------------------------
    assign title_addr = (hcount >= 10'd160 && vcount >= 10'd120) ?
                        17'(vcount - 10'd120) * 17'd320 + 17'(hcount - 10'd160) : 17'd0;

    // -------------------------------------------------------------------------
    // Module Instantiations
    // -------------------------------------------------------------------------

    // PLL: generates 25MHz VGA pixel clock from 50MHz system clock
    clock_gen pll_inst (.refclk(clock), .rst(~reset_n), .outclk_0(vga_clk_int), .locked());
    assign vga_clock = vga_clk_int;

    // VGA controller: generates sync signals and beam position (hcount/vcount)
    vga_controller vga_inst (.vga_clock(vga_clk_int), .reset_n(reset_n), .sync_n(sync_n),
        .blank_n(blank_n), .hsync_n(hsync_n), .vsync_n(vsync_n), .hcount(hcount), .vcount(vcount));

    // Maze ROM: 1-bit per pixel maze image; also provides col_pixel for collision detection
    image_rom rom_inst (.clk(vga_clk_int), .clk50(clock), .addr(vga_addr), .pixel_out(pixel_data),
        .col_addr(col_addr), .col_pixel(col_pixel));

    // Dot state RAM: 307,200-bit RAM tracking which dot pixels are still alive
    dot_state dots_inst (.clk(clock), .reset_n(reset_n), .read_addr(vga_addr), .dot_alive(dot_alive),
        .eat(eat), .eat_addr(eat_addr), .dot_eaten(dot_eaten));

    // ADC controller: reads joystick via SPI, outputs 12-bit LR and UD values
    adc_controller adc_inst (.system_clock(clock), .reset_n(reset_n), .sdo(SDO), .cs_n(CS_N),
        .sclk(SCLK), .sdi(SDI), .joystick_lr(joystick_lr), .joystick_ud(joystick_ud));

    // Pac-Man controller: moves 1px every 8ms, checks walls via col_pixel, detects dot eating
    pac_controller pac_inst (.clock(clock), .reset_n(reset_n), .joystick_lr(joystick_lr),
        .joystick_ud(joystick_ud), .pac_x(pac_x), .pac_y(pac_y), .direction(direction),
        .col_addr(col_addr), .col_pixel(col_pixel), .eat(eat), .eat_addr(eat_addr),
        .moving_out(moving_out), .pac_tile_x(pac_tile_x), .pac_tile_y(pac_tile_y));

    // Ghost 1: follows hardcoded waypoint array extracted from Paint-drawn path
    ghost_controller ghost_inst (.clock(clock), .reset_n(reset_n), .game_active(game_active),
        .pac_x(pac_x), .pac_y(pac_y), .pac_dir(direction),
        .ghost_x(ghost_x), .ghost_y(ghost_y), .ghost_dir(ghost_dir));

    // Ghost 2 (red): circular replay buffer — replays Pac-Man's position history with delay
    random_ghost_controller rghost_inst (.clock(clock), .reset_n(reset_n), .game_active(game_active),
        .col_pixel(col_pixel), .ghost_x(rghost_x), .ghost_y(rghost_y),
        .ghost2_dir(ghost2_dir), .col_addr_out());

    // Ghost 3: follows hardcoded waypoint array
    ghost3_controller ghost3_inst (.clock(clock), .reset_n(reset_n), .game_active(game_active),
        .ghost_x(ghost3_x), .ghost_y(ghost3_y), .ghost3_dir(ghost3_dir));

    // Ghost 4: follows hardcoded waypoint array
    ghost4_controller ghost4_inst (.clock(clock), .reset_n(reset_n), .game_active(game_active),
        .ghost_x(ghost4_x), .ghost_y(ghost4_y), .ghost4_dir(ghost4_dir));

    // Score tracker: increments on each dot_eaten pulse; win triggered at 14256
    score_tracker score_inst (.clock(clock), .reset_n(reset_n), .dot_eaten(dot_eaten), .score(score));

    // Screen image ROMs: 320x240 1-bit images for title, lose, and win screens
    title_rom title_inst (.vga_clk(vga_clk_int), .addr(title_addr), .pixel_out(title_pixel));
    lose_rom  lose_inst  (.vga_clk(vga_clk_int), .addr(title_addr), .pixel_out(lose_pixel));
    win_rom   win_inst   (.vga_clk(vga_clk_int), .addr(title_addr), .pixel_out(win_pixel));

    // PWM audio: Pac-Man theme on title screen, waka waka during gameplay
    pwm2       music_inst (.clock(clock), .reset_n(reset_n), .increase(1'b0), .decrease(1'b0), .pwm_out(music_out));
    waka_sound waka_inst  (.clock(clock), .reset_n(reset_n), .pwm_out(waka_out));

    // Pattern generator: computes RGB for every pixel each clock cycle
    // In cheat mode, ghost coordinates set to 700 (off-screen) so they are not rendered
    pattern_generator pattern_inst (.vga_clock(vga_clk_int), .reset_n(reset_n),
        .hcount(hcount), .vcount(vcount), .pac_x(pac_x), .pac_y(pac_y),
        .ghost_x (cheat_mode ? 10'd700 : ghost_x),
        .ghost_y (cheat_mode ? 10'd700 : ghost_y),
        .rghost_x(cheat_mode ? 10'd700 : rghost_x),
        .rghost_y(cheat_mode ? 10'd700 : rghost_y),
        .ghost3_x(cheat_mode ? 10'd700 : ghost3_x),
        .ghost3_y(cheat_mode ? 10'd700 : ghost3_y),
        .ghost4_x(cheat_mode ? 10'd700 : ghost4_x),
        .ghost4_y(cheat_mode ? 10'd700 : ghost4_y),
        .direction(direction), .ghost_dir(ghost_dir), .ghost2_dir(ghost2_dir),
        .ghost3_dir(ghost3_dir), .ghost4_dir(ghost4_dir),
        .pixel_data(pixel_data), .dot_alive(dot_alive), .game_over(game_over),
        .win(win), .title_active(title_active),
        .title_pixel(title_pixel), .lose_pixel(lose_pixel), .win_pixel(win_pixel),
        .game_state(game_state),
        .vga_addr(vga_addr), .red(red), .green(green), .blue(blue));

    // Seven-segment score display split across HEX0-HEX5
    hex_display12bit score_low  (.value(score[11:0]),          .HEX2(HEX2), .HEX1(HEX1), .HEX0(HEX0));
    hex_display12bit score_high (.value({8'b0, score[15:12]}), .HEX2(HEX5), .HEX1(HEX4), .HEX0(HEX3));

endmodule
